// src/lib/tokens.ts

export type ColumnType = 'new' | 'final' | 'migrated';

export interface TokenMetric {
  value: string;
  color: 'green' | 'red' | 'blue' | 'slate';
  label?: string;
}

export interface Token {
  id: string;
  column: ColumnType;
  name: string;
  ticker: string;
  address: string;
  imgUrl: string; // Placeholder for character images

  // Time & Status
  createdAgo: number; // in seconds, will auto-increment
  badges: string[]; // ['DS', 'Bonding: 99.8%']

  // Core Metrics
  mc: number; // Market Cap
  vol: number; // Volume
  txCount: number;
  price: number;

  // Micro-metrics (The small badges/pills)
  holders: number;
  buyPressure: number; // 0-100, determines the bar width
  change1m: number; // % change
  change5m: number; // % change

  isHot: boolean; // Adds a fire icon or distinct border
}

// AutoGenerated Tokens
const PREFIXES = [
  // --- English (Modern / Tech / Finance) ---
  'Quantum',
  'Ever',
  'Prime',
  'Nova',
  'Pulse',
  'Titan',
  'Vortex',
  'Astra',
  'Hyper',
  'Crystal',
  'Eclipse',
  'Velocity',
  'Carbon',
  'Neon',
  'Vector',
  'Halo',
  'Eon',
  'Sierra',
  'Atlas',
  'Fusion',
  'Vertex',
  'Nimbus',
  'Radiant',
  'Onyx',
  'Solar',
  'Vanguard',
  'Spectra',
  'Orbit',
  'Zenith',
  'Phoenix',
  'Cobalt',
  'Cipher',
  'Aurora',
  'Stellar',
  'Matrix',
  'Echo',
  'Drift',
  'Momentum',
  'Blaze',
  'Gravity',
  'Stratos',
  'Lumen',
  'Flux',
  'Element',
  'Catalyst',
  'Glide',
  'Aether',
  'Mirage',
  'Vivid',
  'Delta',
  'Grail',
  'Infina',
  'MetaCore',
  'ArcLight',
  'Horizon',
  'TerraCore',
  'Ion',
  'Radiance',
  'Sonic',
  'Lattice',
  'Fractal',
  'NimbusX',
  'Scalar',
  'Monolith',
  'Iron',
  'Zephyr',
  'Magna',
  'Forge',
  'Apex',
  'Crown',
  'Beacon',
  'Paragon',

  // --- French ---
  'Lumière',
  'Éclat',
  'Soleil',
  'Nouveau',
  'Renard',
  'Sérénité',
  'Arcène',
  'Marée',
  'Brume',

  // --- Chinese ---
  '星河', // Galaxy
  '未来', // Future
  '光速', // Lightspeed
  '无极', // Infinite
  '天启', // Revelation
  '星云', // Nebula
  '龙影', // Dragon Shadow
  '白虎', // White Tiger

  // --- Japanese ---
  '暁', // Dawn
  '光', // Light
  '未来', // Future
  '天照', // Amaterasu (sun goddess)
  '黒猫', // Black Cat
  '霧雨', // Mist Rain
  '桜風', // Sakura Wind
  '雷鳴', // Thunderclap
];

const SUFFIXES = [
  'Protocol',
  'Chain',
  'Labs',
  'Networks',
  'AI',
  'Finance',
  'Markets',
  'Capital',
  'Hub',
  'Core',
  'Systems',
  'Industries',
  'Solutions',
  'Exchange',
  'Bridge',
  'Vault',
  'Cloud',
  'Engine',
  'Analytics',
  'Tech',
  'ProtocolX',
  'Dynamics',
  'Flow',
  'Grid',
  'Sphere',
  'Terminal',
  'NetworkX',
  'Infinity',
  'Works',
  'Prime',
  'Reserve',
  'Matrix',
  'Framework',
  'Station',
  'Layer',
  'Foundry',
  'Collective',
  'Paradox',
  'Cluster',
  'Pulse',
  'Beacon',
  'Forge',
  'Compute',
  'Logic',
  'Node',
  '–MarketsX',
  'Verse',
  'Genesis',
  'Nexus',
  'Union',
  'Archive',
  'Spectrum',
  'EngineX',
  'Foundation',
  'Arena',

  // --- French ---
  '–Élite',
  'Marché',
  'Système',
  'Finance',
  'Collectif',
  'Atelier',
  'Réserve',

  // --- Chinese ---
  '-科技', // Technology
  '资本', // Capital
  '协议', // Protocol
  '网络', // Network
  '联盟', // Alliance
  '云端', // Cloud

  // --- Japanese ---
  '研究所', // Institute/Labs
  '市場', // Market
  '社', // Company
  '機構', // Agency
  '財団', // Foundation
  '統合', // Unified/Integrations
  '基地', // Base
];

// Helper to generate random float
const random = (min: number, max: number) => Math.random() * (max - min) + min;
const randInt = (min: number, max: number) => Math.floor(random(min, max));
const choice = <T>(arr: T[]): T => arr[randInt(0, arr.length)];

export function generateMockTokens(count: number = 300): {
  [key in ColumnType]: Token[];
} {
  const tokens: Token[] = [];

  for (let i = 0; i < count; i++) {
    const isNew = i < 100;
    const isFinal = i >= 100 && i < 200;
    const column: ColumnType = isNew ? 'new' : isFinal ? 'final' : 'migrated';

    // Realistic MC distribution based on column
    const baseMc = isNew ? 5000 : isFinal ? 50000 : 500000;
    const mc = baseMc * random(0.5, 5);

    tokens.push({
      id: `token-${i}`,
      column,
      name: `${choice(PREFIXES)}${choice(SUFFIXES)}`,
      ticker: choice(SUFFIXES).toUpperCase(),
      address: Math.random().toString(36).substring(2, 8) + '...pump',
      // Use small local avatars from /public/1-55.jpg for realistic visuals
      imgUrl: `/${randInt(1, 70)}.jpg`,

      createdAgo: isNew ? randInt(0, 120) : randInt(300, 86400),
      badges: Math.random() > 0.7 ? ['DS', 'Bonding: 98%'] : [],

      mc,
      vol: mc * random(0.1, 0.5),
      txCount: randInt(5, 5000),
      price: random(0.0000001, 0.01),

      holders: randInt(10, 1000),
      buyPressure: random(20, 90),
      change1m: random(-10, 20),
      change5m: random(-30, 50),

      isHot: Math.random() > 0.9,
    });
  }

  return {
    new: tokens
      .filter((t) => t.column === 'new')
      .sort((a, b) => a.createdAgo - b.createdAgo),
    final: tokens
      .filter((t) => t.column === 'final')
      .sort((a, b) => b.mc - a.mc),
    migrated: tokens
      .filter((t) => t.column === 'migrated')
      .sort((a, b) => b.mc - a.mc),
  };
}
